import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { JSDOM } from 'jsdom';
const html=await readFile(new URL('./dist/card.html',import.meta.url),'utf8');
assert.match(html,/prefers-color-scheme:dark/);
assert.match(html,/@media\(max-width:390px\)/);
const bundle=html.match(/<script type="module">([\s\S]*?)<\/script>/)?.[1];assert.ok(bundle);
const sample=JSON.parse(execFileSync('python3',['scripts/wanxiangli.py','--date','2026-09-23','--user-id','demo','--format','json'],{cwd:new URL('../',import.meta.url),encoding:'utf8'}));
const dom=new JSDOM(html.replace(/<script type="module">[\s\S]*?<\/script>/,''),{url:'https://example.org/',runScripts:'outside-only',pretendToBeVisual:true});
const {window}=dom;let writes=0,redraws=0;window.openai={callTool(){redraws++},toolOutput:sample,widgetState:{privateContent:{open:[]}},setWidgetState(value){this.widgetState=value;writes++}};
window.eval(bundle);
const doc=window.document;
assert.equal(doc.querySelector('h1').textContent,`今日 · ${sample.rating.rating}`);
assert.equal(doc.querySelectorAll('details.panel').length,9);
assert.equal(doc.querySelectorAll('details.panel[open]').length,0);
const first=doc.querySelector('details.panel');first.open=true;first.dispatchEvent(new window.Event('toggle',{bubbles:true}));
assert.equal(doc.querySelectorAll('details.panel[open]').length,1);
const all=[...doc.querySelectorAll('button')].find(b=>b.textContent==='全部展开');all.click();
assert.equal(doc.querySelectorAll('details.panel[open]').length,9);
const none=[...doc.querySelectorAll('button')].find(b=>b.textContent==='全部收起');none.click();
assert.equal(doc.querySelectorAll('details.panel[open]').length,0);
assert.ok(writes>0);assert.equal(redraws,0);
assert.equal(doc.querySelector('details[data-key=daoism] .inside p').textContent.includes(sample.four_signs.daoism.verse),true);
console.log('UI: nine panels, local disclosure, all-open/closed, source content, widget state, mobile/dark CSS OK');
window.close();
